apiVersion: v1
kind: ServiceAccount
metadata:
  name: ip-tables-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ip-tables-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: ip-tables-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: ip-tables-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ip-tables-clusterrole
rules:
- apiGroups:
  - ''
  resources:
  - 'nodes'
  verbs: ["get", "patch"]