apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cilium-cni
configMapGenerator:
- name: values
  namespace: flux-system
  files:
  - values.yaml
- name: cni-install-job
  namespace: flux-system
  files:
  - entrypoint.sh
  - k8s-unmanaged.sh
  - manage-ipsec-keys.sh
resources:
- cilium-release.yaml
- cilium-repo.yaml
- post-install-rbac.yaml
- post-install-job.yaml
- ip-tables-daemonset.yaml
- ip-tables-rbac.yaml
- cilium-ipsec-keys.yaml
generatorOptions:
  disableNameSuffixHash: true