# -- Configure the key of the taint indicating that Cilium is not ready on the node.
# When set to a value starting with `ignore-taint.cluster-autoscaler.kubernetes.io/`, the Cluster Autoscaler will ignore the taint on its decisions, allowing the cluster to scale up.
agentNotReadyTaintKey: "node.cilium.io/agent-not-ready"
encryption:
  enabled: true
  nodeEncryption: false
  type: ipsec
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDR: "100.64.0.0/16"
    clusterPoolIPv4MaskSize: 24
